name: Build and deploy tutor
on:
  push:
    branches: [ "community-theme.palm" ]

jobs:
  deploy:
    permissions:
      actions: write
    runs-on: ubuntu-latest

    steps:
      - name: Trigger community-theme-tutor pipeline
        run: |
          curl --request POST --form token=${{ secrets.GITLAB_PIPELINE_TOKEN }} --form ref=main https://gitlab.com/api/v4/projects/48712583/trigger/pipeline
